# Generated by Django 5.2.5 on 2025-08-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_video',
            field=models.FileField(blank=True, help_text='Event video (mp4, mov, avi, webm)', null=True, upload_to='event_videos/'),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='allowed_photo_formats',
            field=models.JSONField(default=['jpg', 'png', 'heic']),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='allowed_video_formats',
            field=models.JSONField(default=['mp4', 'mov']),
        ),
    ]
