# Generated by Django 5.2.5 on 2025-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='contributor_code',
            field=models.CharField(blank=True, help_text='Unique code for contributors to access this event', max_length=10, null=True, unique=True),
        ),
    ]
