# Generated by Django 5.2.5 on 2025-08-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_contributor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False, help_text='If True, event can be accessed without contributor code'),
        ),
    ]
