# Generated by Django 5.2.5 on 2025-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_banner',
            field=models.ImageField(blank=True, help_text='Event banner image for header display', null=True, upload_to='event_banners/'),
        ),
    ]
