# Generated by Django 5.2.5 on 2025-10-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_package_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_guests',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_photos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_videos',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
