# Generated by Django 5.2.5 on 2025-10-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_voice_recording_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsettings',
            name='allowed_voice_formats',
            field=models.JSONField(default=['mp3', 'wav', 'm4a', 'aac']),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='max_voice_duration',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='max_voice_size',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(blank=True, help_text='Package description for customers', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="List of features as JSON array (e.g., ['QR Code', 'Analytics', 'Support'])", null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this package is available for selection'),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_guests',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of guests allowed. Leave empty for unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_photos',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of photos allowed. Leave empty for unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_videos',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of videos allowed. Leave empty for unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(help_text='Package name (e.g., Basic, Premium, Enterprise)', max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Package price in ETB', max_digits=10),
        ),
    ]
