# Generated by Django 5.2.5 on 2025-10-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_eventsettings_allowed_voice_formats_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsettings',
            name='max_media_per_post',
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='max_image_per_post',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of images per guest post'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='max_video_per_post',
            field=models.PositiveIntegerField(default=2, help_text='Maximum number of videos per guest post'),
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='max_voice_per_post',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of voice recordings per guest post'),
        ),
    ]
