# Generated by Django 5.2.5 on 2025-10-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_eventsettings_max_media_per_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='max_voice',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of voice recordings allowed. Leave empty for unlimited.', null=True),
        ),
    ]
