# Generated by Django 5.2.5 on 2025-10-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_package_max_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsettings',
            name='max_photo_size',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='max_posts_per_guest',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventsettings',
            name='max_voice_size',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
