# Generated by Django 5.2.5 on 2025-11-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_eventsettings_max_photo_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Identifier used in code/integrations', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for the payment method', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('account_number', models.CharField(blank=True, help_text='Optional receiving account number or wallet ID', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
