# Generated by Django 5.2.5 on 2025-11-17 13:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Package description for customers', null=True),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed payment instructions shown to users', null=True),
        ),
    ]
