# Generated by Django 5.2.5 on 2025-11-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_package_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_try',
            field=models.BooleanField(default=False, help_text='If true, events created with this package are activated immediately without payment'),
        ),
    ]
