# Generated by Django 5.2.5 on 2025-11-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_package_is_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsettings',
            name='is_validation_per_guest',
            field=models.BooleanField(
                default=False,
                help_text="If enabled, validation is enforced per guest submission; if disabled, media limits apply globally."
            ),
        ),
    ]
