# Generated by Django 5.2.5 on 2025-11-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_eventsettings_is_validation_per_guest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsettings',
            name='is_validation_per_guest',
        ),
        migrations.AddField(
            model_name='eventsettings',
            name='make_validation_per_media',
            field=models.BooleanField(default=False, help_text="If enabled, users' media is validated per media type (images, videos, voice). If disabled, they can apply any media with the value set in max_posts_per_guest"),
        ),
    ]
